### PR TITLE
Added 'met_dir' in the general options

### PR DESCRIPTION
**Pull request by DrMenny**
Added 3 lines to recognise 'met_dir' as an option in the settings_file. 
This is useful in situations where acolite is installed in an environment without root permission (eg conda package in a VM) where the software cannot write in the path decided inside the config.txt and the config.txt cannot be changed.
The new lines added also allow to choose the met_dirin each computation without changing permanently the config.txt.

### CODE REVIEW

**Comment by acolite** [comment]
Good call - maybe this fits better in the acolite_run.py script, since both CLI and GUI call that one?

**Comment by DrMenny** [comment]
Thank you. I just moved the lines in the acolite_run.py script. Should be ok now

**Comment by acolite** [comment]
Thanks for the suggestion, I tested and added this to the main repository.

**Comment by DrMenny** [comment]
You're welcome

**Pull request closed without merging**
